name: Developer_branch_CI
on:
  push:
    branches:
      - 'XPNS-*'
jobs:
  checks-bats-version:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - run: ls
      - run: tail index.js